version: '{build}'
configuration:
  - Debug
  - Release
build_script:
  - echo "Building for %CONFIGURATION%"
  - ps: .\build.ps1 %CONFIGURATION%
artifacts:
  - path: .\Artifacts\*.nupkg
    name: NuGet
test_script:
  - ps: .\test.ps1
cache:
  - '%USERPROFILE%\.nuget\packages'
